Add AMQP Metrics and Spans
pixie-io/pixie-plugin pull request #41
Opened 2022-11-12 00:46 UTC by philkuz

2022-11-14 21:32 UTC, htroisi requested changes
Update the `start_time` and `end_time` calculations to match these: https://github.com/pixie-io/pixie-plugin/pull/43

2022-11-15 19:44 UTC, philkuz commented
> Update the `start_time` and `end_time` calculations to match these: #43

We don't collect latency at the moment so we don't have a way to calculate the end_time

2022-11-18 00:19 UTC, htroisi approved these changes

2022-11-18 17:37 UTC, aimichelle approved these changes

2022-11-18 17:37 UTC, merged