Add node_name and deployment_name to Redis export scripts.
pixie-io/pixie-plugin pull request #49
Opened 2022-12-12 06:37 UTC by htroisi

Signed-off-by: Hannah Troisi <htroisi@pixielabs.ai>

2022-12-14 22:49 UTC, philkuz requested changes

2022-12-14 22:49 UTC, philkuz commented on plugins/new-relic/retention.yaml
> +      df = df.groupby(['req_cmd', 'source_pod', 'source_service', 'source_namespace', 'destination_pod', 'destination_node', 'destination_deployment','destination_service', 'destination_namespace']).
what about source_node and source_deployment?

2022-12-15 01:37 UTC, philkuz approved these changes

2022-12-15 18:49 UTC, aimichelle approved these changes

2022-12-15 18:49 UTC, merged