Add node_name and deployment_name to AMQP export scripts.
pixie-io/pixie-plugin pull request #50
Opened 2022-12-12 07:59 UTC by htroisi

This PR adds more metadata (node name, deployment name) to the AMQP Span and AMQP Metrics export scripts.

2022-12-14 22:49 UTC, philkuz requested changes

2022-12-14 22:49 UTC, philkuz commented on plugins/new-relic/retention.yaml
> +      df = df.groupby(['source_pod', 'source_service', 'source_namespace', 'destination_pod', 'destination_node',
missing source_node and source_deployment

2022-12-15 01:38 UTC, philkuz approved these changes

2022-12-15 18:49 UTC, aimichelle approved these changes

2022-12-15 18:49 UTC, merged